/*
 * Generated by erpcgen 1.3.0 on Tue Nov 22 18:09:25 2016.
 *
 * AUTOGENERATED - DO NOT EDIT
 */

#if !defined(_test_arithmetic_server_h_)
#define _test_arithmetic_server_h_


#ifdef __cplusplus
#include "test_arithmetic.h"
#include "server.h"
#include <stdint.h>
#include <stdbool.h>


/*!
 * @brief Service subclass for Arithmetic.
 */
class Arithmetic_service : public erpc::Service
{
public:
    Arithmetic_service() : Service(kArithmetic_service_id) {}

    /*! @brief Call the correct server shim based on method unique ID. */
    virtual erpc_status_t handleInvocation(uint32_t methodId, uint32_t sequence, erpc::Codec * codec);

private:
    /*! @brief Server shim for add of Arithmetic interface. */
    erpc_status_t add_shim(erpc::Codec * codec, uint32_t sequence);

    /*! @brief Server shim for sub of Arithmetic interface. */
    erpc_status_t sub_shim(erpc::Codec * codec, uint32_t sequence);
};

extern "C" {
#endif

typedef void * erpc_service_t;

erpc_service_t create_Arithmetic_service(void);
#ifdef __cplusplus
}
#endif

#endif // _test_arithmetic_server_h_
