# Makefile for building the tock kernel for the signpost debug radio module

PLATFORM=debug_radio_module

# the current directory
SIGNPOST_PLATFORM_DIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))

include $(SIGNPOST_PLATFORM_DIR)/../Signpost-SAM4L-kernel.mk

