# Makefile for building the tock kernel for the signpost radio module

PLATFORM=radio_module

# the current directory
SIGNPOST_PLATFORM_DIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))

include $(SIGNPOST_PLATFORM_DIR)/../Signpost-SAM4L-kernel.mk

