# Makefile for building the tock kernel for the signpost audio module

PLATFORM=audio_module

# the current directory
SIGNPOST_PLATFORM_DIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))

include $(SIGNPOST_PLATFORM_DIR)/../Signpost-SAM4L-kernel.mk

