#!/usr/bin/env bash

set -e
set -x

make -C erpc clean

make -j -C erpc/erpcgen

make -C erpc/erpcgen PREFIX=./$(uname) install

# Their PREFIX behavior is annoying - work around
mkdir -p bin/$(uname)
mv erpc/erpcgen/$(uname)/bin/erpcgen bin/$(uname)/
rm -r erpc/erpcgen/$(uname)

