#!/usr/bin/env bash

set -e
set -x

rm -rf build

make -f CreateLibERPC.mk TOCK_ARCH=cortex-m0 V=1
make -f CreateLibERPC.mk TOCK_ARCH=cortex-m4 V=1

mkdir -p liberpc/cortex-m0
mkdir -p liberpc/cortex-m4

cp build/cortex-m0/liberpc.a liberpc/cortex-m0/
cp build/cortex-m4/liberpc.a liberpc/cortex-m4/

