#!/usr/bin/env bash

set -e
set -x

make -C erpc clean

# This is a bit of a hack that should probably be revisited eventually
if [ $(uname) == "Linux" ]; then
  pushd erpc
  patch mk/targets.mk < ../static_erpcgen.patch
  popd
fi

make -j -C erpc/erpcgen

make -C erpc/erpcgen PREFIX=./$(uname) install

# Their PREFIX behavior is annoying - work around
mkdir -p bin/$(uname)
mv erpc/erpcgen/$(uname)/bin/erpcgen bin/$(uname)/
rm -r erpc/erpcgen/$(uname)

if [ $(uname) == "Linux" ]; then
  pushd erpc
  patch -R mk/targets.mk < ../static_erpcgen.patch
fi

