# Makefile for building the tock kernel for the signpost controller

PLATFORM=controller

# the current directory
SIGNPOST_PLATFORM_DIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))

include $(SIGNPOST_PLATFORM_DIR)/../Signpost-SAM4L-kernel.mk

